### ISSUE TITLE
运行muilt_vehicles.py报错

### ISSUE THREAD

**Issue by tang-agui** [mmmmaomao/Carla0.9.10-kitti-data-export#4]
你好！
首先我将下载下来的0.9.10解压后放到本项目下面，然后`python muilt_ vehicles.py`运行，结果报错：

![图片](https://user-images.githubusercontent.com/61316384/115150013-266c3c00-a099-11eb-9e89-2370263e6dca.png)

然后我在本地单独运行.exe启动后，运行`PythonAPI/examples`文件是可以的，请问怎么解决呢？

**Comment by tang-agui** [comment]
问题已解决。

**Comment by mmmmaomao** [comment]
linux下放在PythonAPI文件夹中&nbsp;




------------------




王杰

北京邮电大学/本科生/现代邮政学院



13121815757

北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "tang-agui"; 
Date: 2021年4月18日(星期天) 晚上10:56
To: "mmmmaomao/Carla0.9.10-kitti-data-export"; 
Cc: "Subscribed"; 
Subject: [mmmmaomao/Carla0.9.10-kitti-data-export] 运行muilt_vehicles.py报错 (#4)

&nbsp;


 
你好！
 首先我将下载下来的0.9.10解压后放到本项目下面，然后python muilt_ vehicles.py运行，结果报错：
 

 
然后我在本地单独运行.exe启动后，运行PythonAPI/examples文件是可以的，请问怎么解决呢？

**Comment by tang-agui** [comment]
> 
> linux下放在PythonAPI文件夹中&nbsp;
> […](#)
> ------------------ 王杰 北京邮电大学/本科生/现代邮政学院 13121815757 北京 &nbsp; &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: "tang-agui"; Date: 2021年4月18日(星期天) 晚上10:56 To: "mmmmaomao/Carla0.9.10-kitti-data-export"; Cc: "Subscribed"; Subject: [mmmmaomao/Carla0.9.10-kitti-data-export] 运行muilt_vehicles.py报错 (#4) &nbsp; 你好！ 首先我将下载下来的0.9.10解压后放到本项目下面，然后python muilt_ vehicles.py运行，结果报错： 然后我在本地单独运行.exe启动后，运行PythonAPI/examples文件是可以的，请问怎么解决呢？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢回复，我是在Windows下运行，后来解决了，是因为没有改.egg文件，还有python版本的问题。
